#!/bin/bash

echo "📱 GUÍA PASO A PASO - GITHUB + RENDER GRATUITO"
echo "=============================================="
echo ""
echo "🔥 PASO 1: CREAR REPOSITORIO EN GITHUB"
echo "1. Ve a: https://github.com"
echo "2. Haz clic en '+' → 'New repository'"
echo "3. Nombre: dashboard-energia-xm"
echo "4. Descripción: Dashboard energético XM Colombia"
echo "5. ✅ Public (para deploy gratis)"
echo "6. ❌ NO marques 'Add a README file'"
echo "7. Clic en 'Create repository'"
echo ""
echo "🚀 PASO 2: CONECTAR TU CÓDIGO CON GITHUB"
echo "Copia y pega estos comandos EN ORDEN:"
echo ""
echo "git remote add origin https://github.com/TU-USUARIO/dashboard-energia-xm.git"
echo "git branch -M main"  
echo "git push -u origin main"
echo ""
echo "📝 NOTA: Reemplaza 'TU-USUARIO' con tu nombre de usuario de GitHub"
echo ""
echo "🌐 PASO 3: DESPLEGAR EN RENDER.COM (GRATIS)"
echo "1. Ve a: https://render.com"
echo "2. 'Sign Up' (gratis) con tu GitHub"
echo "3. Dashboard → 'New Web Service'"
echo "4. 'Connect a repository'"
echo "5. Busca 'dashboard-energia-xm' → 'Connect'"
echo "6. Configuración:"
echo "   - Name: dashboard-energia-xm"
echo "   - Branch: main"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: python app.py"
echo "7. 'Create Web Service'"
echo ""
echo "⏳ PASO 4: ESPERAR DEPLOY (5-10 minutos)"
echo "Render instalará Python, descargará dependencias y ejecutará tu app"
echo ""
echo "🎉 PASO 5: ¡TU URL ESTARÁ LISTA!"
echo "https://dashboard-energia-xm.onrender.com"
echo ""
echo "💡 BONUS: MANTENER DESPIERTA LA APP (OPCIONAL)"
echo "1. Ve a: https://uptimerobot.com"
echo "2. Sign up gratis"
echo "3. 'Add New Monitor'"
echo "4. Tipo: HTTP(s)"
echo "5. URL: tu URL de Render"
echo "6. Monitoring Interval: 5 minutes"
echo "7. ¡Tu app nunca se dormirá!"
echo ""
echo "✅ RESULTADO FINAL:"
echo "- Dashboard público 24/7"
echo "- HTTPS automático"
echo "- Gratis para siempre"
echo "- Auto-restart si se crashea"
echo "- URL profesional"
