#!/bin/bash

echo "🆓 DESPLEGANDO DASHBOARD GRATIS EN RENDER.COM"
echo "============================================="

# Commit cambios si los hay
echo "📦 Guardando cambios..."
git add .
git commit -m "Configurado para Render.com - Deploy gratuito" || echo "No hay cambios nuevos"

echo ""
echo "🎯 OPCIONES GRATUITAS DISPONIBLES:"
echo ""
echo "1️⃣  RENDER.COM (RECOMENDADO):"
echo "   ✅ 100% Gratis para siempre"
echo "   ✅ Auto-restart si se crashea"
echo "   ✅ SSL automático"
echo "   ⚠️  Se 'duerme' tras 15 min sin uso"
echo "   ⚡ Se 'despierta' en 30 segundos"
echo ""
echo "2️⃣  RAILWAY.APP:"
echo "   ✅ $5/mes crédito gratis"
echo "   ✅ Más rápido que Render"
echo "   ✅ No se duerme"
echo "   ⚠️  Crédito se agota si hay mucho tráfico"
echo ""
echo "📋 PASOS PARA RENDER.COM:"
echo "1. Ve a: https://render.com"
echo "2. Sign up (gratis)"
echo "3. 'New Web Service'"
echo "4. Conecta tu GitHub"
echo "5. Configuración automática:"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: python app.py"
echo "6. ¡Deploy gratuito!"
echo ""
echo "📋 PASOS PARA RAILWAY.APP:"
echo "1. Ve a: https://railway.app"
echo "2. 'Deploy from GitHub'"
echo "3. ¡Automático!"
echo ""
echo "🔗 RESULTADO:"
echo "Tu dashboard estará en una URL como:"
echo "- https://dashboard-xm-xxxx.onrender.com (Render)"
echo "- https://dashboard-xm-xxxx.up.railway.app (Railway)"
echo ""
echo "💡 TIP: Para evitar que se 'duerma' en Render:"
echo "Usa un servicio como UptimeRobot (gratis) que visite"
echo "tu URL cada 5 minutos para mantenerla 'despierta'"
echo ""
echo "✅ ¡Tu dashboard será GRATIS y estará disponible 24/7!"
